# Dockerfile.dev
FROM golang:1.24-alpine

# Install Git (required by go install), build tools, and Air
RUN apk add --no-cache git build-base curl \
  && go install github.com/air-verse/air@latest
  

WORKDIR /app

COPY . .

# Air will automatically watch changes
CMD ["air"]
